/**
 * groq.ts — Groq API integration for dataset card generation
 *
 * Analyzes a raw data sample and returns a structured dataset card as JSON.
 * Called server-side only (via /api/generate-card route) to protect the API key.
 */

import Groq from "groq-sdk";

const client = new Groq({
  apiKey: process.env.GROQ_API_KEY || "dummy-key-for-build",
});

/**
 * DatasetCard — structured metadata generated by AI about a dataset
 */
export interface DatasetCard {
  summary: string;
  data_type: "tabular" | "text" | "image" | "audio" | "other";
  row_count_estimate: number;
  features: string[];
  use_cases: string[];
  bias_warnings: string[];
  quality_score: number; // 1–10
  recommended_models: string[];
}

/**
 * Generate a rich dataset card by asking Groq to analyze a data sample.
 *
 * Only the first 500 lines are sent to stay within token limits while
 * giving the model enough signal to make accurate assessments.
 *
 * @param sample — raw text content of the dataset (first 500 lines)
 * @returns parsed DatasetCard object
 */
export async function generateDatasetCard(sample: string): Promise<DatasetCard> {
  // Truncate to first 50 lines and 3000 characters for API efficiency
  const truncatedLines = sample.split("\n").slice(0, 50).join("\n");
  const truncated = truncatedLines.length > 3000 ? truncatedLines.slice(0, 3000) : truncatedLines;

  const completion = await client.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "system",
        content: `You are a dataset analyst. Analyze this data sample and return ONLY a JSON object with no markdown: { "summary": "string", "data_type": "tabular|text|image|audio|other", "row_count_estimate": 1000, "features": [], "use_cases": [], "bias_warnings": [], "quality_score": 8, "recommended_models": [] }`,
      },
      {
        role: "user",
        content: truncated,
      },
    ],
    temperature: 0.1,
    response_format: { type: "json_object" },
  });

  const rawText = completion.choices[0]?.message?.content || "";

  // Strip any accidental markdown fences before parsing, just in case
  const cleaned = rawText
    .replace(/^```(?:json)?\n?/m, "")
    .replace(/```$/m, "")
    .trim();

  try {
    const card = JSON.parse(cleaned) as DatasetCard;
    return card;
  } catch {
    throw new Error(`Groq returned invalid JSON: ${rawText.slice(0, 200)}`);
  }
}

/**
 * Chat with a dataset sample using Groq.
 * 
 * @param sample - raw text content of the dataset
 * @param question - user's question
 * @returns AI response text
 */
export async function chatWithDataset(sample: string, question: string): Promise<string> {
  const truncatedLines = sample.split("\n").slice(0, 50).join("\n");
  const truncated = truncatedLines.length > 3000 ? truncatedLines.slice(0, 3000) : truncatedLines;

  const completion = await client.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "system",
        content: `You are an expert data analyst. The user is asking a question about a dataset. Here is a sample of the first 50 rows of the dataset:\n\n${truncated}\n\nAnswer the user's question accurately and concisely based ONLY on the provided sample. If the sample doesn't contain enough information, say so. Do not hallucinate.`,
      },
      {
        role: "user",
        content: question,
      },
    ],
    temperature: 0.2,
  });

  return completion.choices[0]?.message?.content || "I couldn't generate an answer.";
}
